In [1]:
#lambda 
t = lambda var:var*5

In [2]:
t(4)

20

In [3]:
seq= [1,2,3,4,5,6,7,8]

In [4]:
list(map(lambda num:num*4, seq))

[4, 8, 12, 16, 20, 24, 28, 32]

In [7]:
list(filter(lambda num:num%2 !=0, seq))

[1, 3, 5, 7]

In [8]:
s = "Hello my name is morgan"

In [12]:
s.upper()

'HELLO MY NAME IS MORGAN'

In [13]:
s.split()

['Hello', 'my', 'name', 'is', 'morgan']

In [14]:
s.lower()

'hello my name is morgan'

In [17]:
tweet= 'Go sport! #Sports'

In [19]:
tweet.split('#')[1]

'Sports'

In [20]:
d= {'k1':1, 'k2':2}

In [21]:
d.items()

dict_items([('k1', 1), ('k2', 2)])

In [22]:
d.values()

dict_values([1, 2])

In [23]:
lst = [1,2,3,4,5,6,7]

In [24]:
lst

[1, 2, 3, 4, 5, 6, 7]

In [25]:
lst.pop(0)

1

In [26]:
lst.pop()

7

In [27]:
'x' in [1,2,3,'x']

True

In [28]:
x= [(1,2), (3,4), (5,6)]

In [29]:
x[1][1]

4

In [30]:
for item in x:
    print(item)

(1, 2)
(3, 4)
(5, 6)


In [31]:
for (a,b) in x:
    print (b)

2
4
6


In [34]:
for a,b in x:
    print (a)

1
3
5


In [35]:
for a,b in x:
    print (b)

2
4
6


In [36]:
7**4

2401

In [38]:
s = "Hi there Sam!"
lst =  s.split()

In [39]:
lst

['Hi', 'there', 'Sam!']

In [40]:
d= {'k1': [1,2,3,{'tricky':['oh', 'man', 'inception', {'target': [1,2,3,'hello']}]}]}

In [77]:
d.keys()

dict_keys(['k1'])

In [82]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

In [43]:
d.values()

dict_values([[1, 2, 3, {'tricky': ['oh', 'man', 'inception', {'target': [1, 2, 3, 'hello']}]}]])

In [44]:
d.values(0)

TypeError: values() takes no arguments (1 given)

In [47]:
def domainGet(email):
    lst = email.split('@')[1]
    return lst
    

In [48]:
domainGet('morgyken@gmail.com')

'gmail.com'

In [85]:
def findDog(str):
    lst = str.split()
    return 'dog'.lower() in lst
        
        

In [86]:
findDog('Is there a gog here?')

False

In [65]:
seq = ['soup', 'dog', 'salad', 'cat', 'great']

In [66]:
t = lambda var:var.startswith('s')

In [67]:
list(filter(t, seq))

['soup', 'salad']

In [88]:
def cought_speeding(speed, is_birthday):
    if(is_birthday== 'true'): 
        if speed <= 65:
            ticket = 'No Ticket'
        elif speed <= 85: 
            ticket = 'Small Ticket'
        else:
            ticket = 'Big Ticket'
    else:
        if speed <= 60:
            ticket = 'No Ticket'
        elif speed <= 80: 
            ticket = 'Small Ticket'
        else:
            ticket = 'Big Ticket'
    print(ticket)

In [89]:
cought_speeding(81, 'true')

Small Ticket


In [75]:
cought_speeding(120, 'true')

Big Ticket


In [90]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [91]:
#nupy arrays
list = [1,2,3,4]

In [92]:
import numpy as np

In [93]:
arr = np.array(list)

In [94]:
arr

array([1, 2, 3, 4])

In [95]:
my_mat = [[1,2,3], [1,2,4,5,6], [2, 4,5,6]]

In [98]:
np.array(my_mat)

array([list([1, 2, 3]), list([1, 2, 4, 5, 6]), list([2, 4, 5, 6])],
      dtype=object)

In [101]:
np.arange(1,31,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [102]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [105]:
np.ones((7,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [106]:
np.linspace(0,5,12)

array([0.        , 0.45454545, 0.90909091, 1.36363636, 1.81818182,
       2.27272727, 2.72727273, 3.18181818, 3.63636364, 4.09090909,
       4.54545455, 5.        ])

In [107]:
np.eye(4) #indentity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [108]:
np.random.rand(6)

array([0.02654129, 0.34691785, 0.16335568, 0.7576684 , 0.01594678,
       0.2406213 ])

In [109]:
np.random.rand(6,3)

array([[0.9796748 , 0.97341463, 0.56702586],
       [0.97690876, 0.56824648, 0.28304459],
       [0.82569288, 0.36547481, 0.46363773],
       [0.90433864, 0.97353858, 0.71081416],
       [0.76154   , 0.01564293, 0.60005957],
       [0.93662928, 0.54510111, 0.46232247]])

In [112]:
np.random.randn(5,6)

array([[ 0.71375057, -1.55731466,  1.74108133,  1.46798349, -0.27946731,
        -0.09522861],
       [-0.71720332, -1.1237459 ,  0.26197064,  0.58742509, -0.94762665,
        -0.83672603],
       [-0.5878971 ,  0.24004241, -0.46046222,  1.27086033,  0.75946948,
         0.06709151],
       [ 1.45838483, -0.61875629,  1.08598893, -1.85976412,  0.33623538,
        -1.41445251],
       [ 0.50257385, -2.32926203, -1.71549103,  1.39412473, -0.59482211,
        -0.53629439]])

In [116]:
np.random.randint(1,100, 50)

array([39, 10, 71, 32, 68, 71, 10, 54, 93, 95, 46, 47, 55, 25, 90, 65, 16,
       69, 66,  9, 57, 41, 90, 41, 23, 50, 39, 36, 14,  1, 47, 64, 89, 98,
       47, 33,  5, 89,  3, 52, 98, 10, 16, 46, 42, 49, 26, 79, 78, 53])

In [118]:
arr = np.arange(25)

In [119]:
ranrray = np.random.randint(0,50,10)

In [120]:
ranrray

array([11, 48, 10,  5, 45, 13, 39, 37,  9,  4])

In [121]:
ranrray.reshape(5,2)

array([[11, 48],
       [10,  5],
       [45, 13],
       [39, 37],
       [ 9,  4]])

In [122]:
ranrray

array([11, 48, 10,  5, 45, 13, 39, 37,  9,  4])

In [123]:
ranrray.max()

48

In [124]:
ranrray.min()

4

In [125]:
ranrray.argmax()

1

In [126]:
ranrray.argmin()

9

In [127]:
arr = np.arange(0,22)

In [128]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

In [129]:
arr[9]

9

In [130]:
arr[1:5]

array([1, 2, 3, 4])

In [131]:
arr[2:7]

array([2, 3, 4, 5, 6])

In [132]:
arr[7:]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [133]:
arr[0:2]= 200

In [134]:
arr

array([200, 200,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21])

In [140]:
slice_of_arr = arr [0:10]
slice_of_arr[:]

array([200, 200,   2,   3,   4,   5,   6,   7,   8,   9])

In [141]:
slice_of_arr[:5]

array([200, 200,   2,   3,   4])

In [142]:
slice_of_arr[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
arr_copy = arr.copy()

In [144]:
arr_copy

array([200, 200,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21])

In [145]:
arr_copy[:] =200

In [146]:
arr_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200])

In [147]:
arr_2d = np.array([[5,10,15], [20,25,30], [36,40,45]])

In [148]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [36, 40, 45]])

In [150]:
arr_2d[0][0]

5

In [151]:
arr_2d[2][2]

45

In [152]:
arr_2d[1]

array([20, 25, 30])

In [153]:
arr_2d[1][1]

25

In [154]:
arr_2d[2][1]

40

In [155]:
arr_2d[2,1]

40

In [156]:
arr_2d[1,2]

30

In [157]:
arr_2d[:2,1:] # from row 2 and column 2 onwards 

array([[10, 15],
       [25, 30]])

In [158]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [159]:
array2= np.arange(1,11)

In [160]:
array2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [162]:
bool_arr = array2 >4

In [163]:
bool_arr 

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [164]:
array2[array2 >4]

array([ 5,  6,  7,  8,  9, 10])

In [165]:
array2d = np.arange(50).reshape(5,10)

In [166]:
array2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [167]:
array2d[1:3,]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [169]:
array2d[1:3,3:9]

array([[13, 14, 15, 16, 17, 18],
       [23, 24, 25, 26, 27, 28]])

In [170]:
arrz = np.arange(0,11)

In [171]:
arrz +arrz

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [172]:
arrz - arrz

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [173]:
arrz + 7

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [174]:
arrz * 6

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54, 60])

In [175]:
arrz /5

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [176]:
arrz / arrz

C:\conda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [177]:
arrz ** arrz

array([         1,          1,          4,         27,        256,
             3125,      46656,     823543,   16777216,  387420489,
       1410065408], dtype=int32)

In [178]:
arrz ** 3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [179]:
np.sqrt(arrz)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [181]:
np.sqrt(arrz)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [182]:
max(arrz)

10

In [183]:
np.max(arrz)

10