In [ ]:
# https://www.youtube.com/watch?v=OGxgnH8y2NM&list=PLQVvvaa0QuDfKTOs3Keq_kaG2P55YRn5v
# sentdex

In [2]:
#regresion
import pandas as pd
import quandl

In [2]:
pip install quandl

  Using cached https://files.pythonhosted.org/packages/62/1e/a94a8d635fa3ce4cfc7f506003548d0a2447ae76fd5ca53932970fe3053f/pyasn1-0.4.8-py2.py3-none-any.whl
  Created wheel for inflection: filename=inflection-0.3.1-cp37-none-any.whl size=6082 sha256=0adf5ecdabac1702a38985d47fec14f2bb700271c120215742abe8a4299d07d2
  Stored in directory: C:\Users\USER\AppData\Local\pip\Cache\wheels\9f\5a\d3\6fc3bf6516d2a3eb7e18f9f28b472110b59325f3f258fe9211
Successfully built inflection
  Found existing installation: more-itertools 7.2.0
    Uninstalling more-itertools-7.2.0:
      Successfully uninstalled more-itertools-7.2.0
Note: you may need to restart the kernel to use updated packages.


In [3]:
import quandl

In [4]:
df = quandl.get('WIKI/GOOGL')

In [5]:
df

Open     High      Low     Close      Volume  Ex-Dividend  \
Date                                                                       
2004-08-19   100.01   104.06    95.96   100.335  44659000.0          0.0   
2004-08-20   101.01   109.08   100.50   108.310  22834300.0          0.0   
2004-08-23   110.76   113.48   109.05   109.400  18256100.0          0.0   
2004-08-24   111.24   111.60   103.57   104.870  15247300.0          0.0   
2004-08-25   104.76   108.00   103.88   106.000   9188600.0          0.0   
...             ...      ...      ...       ...         ...          ...   
2018-03-21  1092.57  1108.70  1087.21  1094.000   1990515.0          0.0   
2018-03-22  1080.01  1083.92  1049.64  1053.150   3418154.0          0.0   
2018-03-23  1051.37  1066.78  1024.87  1026.550   2413517.0          0.0   
2018-03-26  1050.60  1059.27  1010.58  1054.090   3272409.0          0.0   
2018-03-27  1063.90  1064.54   997.62  1006.940   2940957.0          0.0   

            Split Ratio    Adj. Open    Adj. High     Adj. Low   Adj. Close  \
Date                                                                          
2004-08-19          1.0    50.159839    52.191109    48.128568    50.322842   
2004-08-20          1.0    50.661387    54.708881    50.405597    54.322689   
2004-08-23          1.0    55.551482    56.915693    54.693835    54.869377   
2004-08-24          1.0    55.792225    55.972783    51.945350    52.597363   
2004-08-25          1.0    52.542193    54.167209    52.100830    53.164113   
...                 ...          ...          ...          ...          ...   
2018-03-21          1.0  1092.570000  1108.700000  1087.210000  1094.000000   
2018-03-22          1.0  1080.010000  1083.920000  1049.640000  1053.150000   
2018-03-23          1.0  1051.370000  1066.780000  1024.870000  1026.550000   
2018-03-26          1.0  1050.600000  1059.270000  1010.580000  1054.090000   
2018-03-27          1.0  1063.900000  1064.540000   997.620000  1006.940000   

            Adj. Volume  
Date                     
2004-08-19   44659000.0  
2004-08-20   22834300.0  
2004-08-23   18256100.0  
2004-08-24   15247300.0  
2004-08-25    9188600.0  
...                 ...  
2018-03-21    1990515.0  
2018-03-22    3418154.0  
2018-03-23    2413517.0  
2018-03-26    3272409.0  
2018-03-27    2940957.0  

[3424 rows x 12 columns]

In [11]:
df1 = df[['Open', 'High', 'Low', 'Close', 'Volume']]

In [18]:
df1['HL_PCT'] = (df['High']- df['Close']) / df1['Close'] *100.0

C:\conda\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [19]:
df1

Open     High      Low     Close      Volume  PCT_change  \
Date                                                                      
2004-08-19   100.01   104.06    95.96   100.335  44659000.0    0.324968   
2004-08-20   101.01   109.08   100.50   108.310  22834300.0    7.227007   
2004-08-23   110.76   113.48   109.05   109.400  18256100.0   -1.227880   
2004-08-24   111.24   111.60   103.57   104.870  15247300.0   -5.726357   
2004-08-25   104.76   108.00   103.88   106.000   9188600.0    1.183658   
...             ...      ...      ...       ...         ...         ...   
2018-03-21  1092.57  1108.70  1087.21  1094.000   1990515.0    0.130884   
2018-03-22  1080.01  1083.92  1049.64  1053.150   3418154.0   -2.487014   
2018-03-23  1051.37  1066.78  1024.87  1026.550   2413517.0   -2.360729   
2018-03-26  1050.60  1059.27  1010.58  1054.090   3272409.0    0.332191   
2018-03-27  1063.90  1064.54   997.62  1006.940   2940957.0   -5.353887   

              HL_PCT  
Date                  
2004-08-19  3.712563  
2004-08-20  0.710922  
2004-08-23  3.729433  
2004-08-24  6.417469  
2004-08-25  1.886792  
...              ...  
2018-03-21  1.343693  
2018-03-22  2.921711  
2018-03-23  3.918952  
2018-03-26  0.491419  
2018-03-27  5.720301  

[3424 rows x 7 columns]

In [20]:
df1['PCT_change'] = (df['Close']- df['Open']) / df1['Open'] *100.0

C:\conda\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [21]:
df1

Open     High      Low     Close      Volume  PCT_change  \
Date                                                                      
2004-08-19   100.01   104.06    95.96   100.335  44659000.0    0.324968   
2004-08-20   101.01   109.08   100.50   108.310  22834300.0    7.227007   
2004-08-23   110.76   113.48   109.05   109.400  18256100.0   -1.227880   
2004-08-24   111.24   111.60   103.57   104.870  15247300.0   -5.726357   
2004-08-25   104.76   108.00   103.88   106.000   9188600.0    1.183658   
...             ...      ...      ...       ...         ...         ...   
2018-03-21  1092.57  1108.70  1087.21  1094.000   1990515.0    0.130884   
2018-03-22  1080.01  1083.92  1049.64  1053.150   3418154.0   -2.487014   
2018-03-23  1051.37  1066.78  1024.87  1026.550   2413517.0   -2.360729   
2018-03-26  1050.60  1059.27  1010.58  1054.090   3272409.0    0.332191   
2018-03-27  1063.90  1064.54   997.62  1006.940   2940957.0   -5.353887   

              HL_PCT  
Date                  
2004-08-19  3.712563  
2004-08-20  0.710922  
2004-08-23  3.729433  
2004-08-24  6.417469  
2004-08-25  1.886792  
...              ...  
2018-03-21  1.343693  
2018-03-22  2.921711  
2018-03-23  3.918952  
2018-03-26  0.491419  
2018-03-27  5.720301  

[3424 rows x 7 columns]

In [22]:
finDF = df1[['Close','HL_PCT', 'PCT_change', 'Volume']]

In [23]:
finDF.head()

Close    HL_PCT  PCT_change      Volume
Date                                                 
2004-08-19  100.335  3.712563    0.324968  44659000.0
2004-08-20  108.310  0.710922    7.227007  22834300.0
2004-08-23  109.400  3.729433   -1.227880  18256100.0
2004-08-24  104.870  6.417469   -5.726357  15247300.0
2004-08-25  106.000  1.886792    1.183658   9188600.0

In [ ]:
# end of video 1

In [24]:
import math
forecast_col = 'Close'
finDF.fillna(-9999, inplace=True)
forecast_out = int(math.ceil(0.01 * len(finDF)))

C:\conda\lib\site-packages\pandas\core\frame.py:4244: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  **kwargs


In [25]:
forecast_out

35

In [32]:
finDF['label'] = finDF[forecast_col].shift(-forecast_out)

C:\conda\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [33]:
finDF.head()

Close    HL_PCT  PCT_change      Volume   label
Date                                                         
2004-08-19  100.335  3.712563    0.324968  44659000.0  137.73
2004-08-20  108.310  0.710922    7.227007  22834300.0  135.26
2004-08-23  109.400  3.729433   -1.227880  18256100.0  137.40
2004-08-24  104.870  6.417469   -5.726357  15247300.0  140.90
2004-08-25  106.000  1.886792    1.183658   9188600.0  142.00

In [34]:
finDF.dropna(inplace = True)
finDF.tail()

C:\conda\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


Close    HL_PCT  PCT_change     Volume    label
Date                                                         
2018-01-30  1177.37  0.896914   -0.029718  1792602.0  1094.00
2018-01-31  1182.22  0.346805   -0.134312  1643877.0  1053.15
2018-02-01  1181.59  0.495942    0.476195  2774967.0  1026.55
2018-02-02  1119.20  1.081129   -0.729098  5798880.0  1054.09
2018-02-05  1068.76  4.325574   -2.893850  3742469.0  1006.94

In [ ]:
#end of video 2

In [40]:
import numpy as np
from sklearn import preprocessing,svm
#from sklearn.model_selection import cross_validation
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression

In [29]:
finDF.tail()

Close    HL_PCT  PCT_change     Volume
Date                                                
2018-03-21  1094.00  1.343693    0.130884  1990515.0
2018-03-22  1053.15  2.921711   -2.487014  3418154.0
2018-03-23  1026.55  3.918952   -2.360729  2413517.0
2018-03-26  1054.09  0.491419    0.332191  3272409.0
2018-03-27  1006.94  5.720301   -5.353887  2940957.0

In [78]:
#features x, labes y
x= np.array(finDF.drop(['label'],1))
y = np.array(finDF['label'])
x= preprocessing.scale(x)
x= x[:-forecast_out + 1]
x_lately = x[-forecast_out:]
finDF.dropna(inplace= True)

y = np.array(finDF['label'])

C:\conda\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys


In [79]:
x

array([[-2.20869996,  2.35025798,  0.23194449,  4.44790502],
       [-2.17281626, -0.30866295,  4.84146176,  1.80881376],
       [-2.16791178,  2.36520212, -0.80512254,  1.25520764],
       ...,
       [ 2.05880605,  0.22126293, -0.06331827, -0.74860941],
       [ 2.0705948 , -0.5938212 , -0.02888501, -0.78674792],
       [ 2.09795191, -0.13340253,  0.14019752, -0.76716771]])

In [80]:
len(y)

3389

In [81]:
len(x)

3355

In [82]:
y = y [:3355]

In [83]:
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size = 0.2)

In [87]:

#clf= LinearRegression()
#clf= svm.SVR(kernel= 'polynomial')
clf= LinearRegression(n_jobs = -1)
clf.fit(X_train, y_train)
accuracy =clf.score(X_test, y_test)
#clf= svm.SVR()


In [88]:
x_lately


array([[ 1.80093833, -0.67305857,  0.36635407, -0.78693389],
       [ 1.80075835,  0.40986043, -0.4566393 , -0.7313532 ],
       [ 1.99086324,  1.62820645,  0.18851886, -0.330827  ],
       [ 1.98843349, -0.36394505,  0.27253899, -0.68084762],
       [ 1.98802854, -0.25585112,  0.01750147, -0.77210665],
       [ 2.03104399, -0.49150947,  0.41962525, -0.69773114],
       [ 2.03270881, -0.72183563,  0.20628155, -0.80322321],
       [ 2.06429547, -0.88188955,  0.47861463, -0.78659144],
       [ 2.03140395, -0.09649687, -0.39377658, -0.84378487],
       [ 2.07509432, -0.8525581 ,  0.1892502 , -0.80060742],
       [ 2.05408155, -0.67124345, -0.00292787, -0.7375154 ],
       [ 2.03801825, -0.72801895,  0.03282929, -0.83681939],
       [ 2.02474465, -0.29693282,  0.04058215, -0.84173464],
       [ 2.02672444, -0.88228685,  0.26719602, -0.83352039],
       [ 2.00319193, -0.66319969,  0.10589768, -0.84344653],
       [ 2.05745619, -0.66045124,  0.63984807, -0.81620276],
       [ 2.00085218,  0.

In [89]:
forecast_set = clf.predict(x_lately)

In [90]:
forecast_set

array([ 970.2007754 ,  964.59634653,  986.03361247, 1003.61258048,
       1004.92858109, 1012.63613086, 1016.66566722, 1022.87807301,
       1014.64430161, 1025.84004892, 1020.13242001, 1018.74785662,
       1013.37922747, 1016.82380479, 1011.38705801, 1020.0758035 ,
       1006.3621315 , 1009.97855636, 1023.45286691, 1025.38565851,
       1028.99425409, 1040.4079611 , 1028.51245994, 1002.40579079,
       1007.12114902,  995.82312262,  981.79188005,  985.42215007,
       1002.45488652, 1015.69302006, 1020.38892817, 1024.44152716,
       1015.56391123, 1023.67978202, 1025.2569694 ])

In [91]:
import matplotlib.pyplot as plt
from matplotlib import style

In [92]:
style.use('ggplot')

In [94]:
import statsmodels.api as sm

In [95]:
pip install xlrd

Note: you may need to restart the kernel to use updated packages.


In [96]:
pip install pydotplus

  Created wheel for pydotplus: filename=pydotplus-2.0.2-cp37-none-any.whl size=24573 sha256=51812d73ddf7883d9c7867b08c6e1248d9cccb60ddd3ffa82c473a09dcc30010
  Stored in directory: C:\Users\USER\AppData\Local\pip\Cache\wheels\35\7b\ab\66fb7b2ac1f6df87475b09dc48e707b6e0de80a6d8444e3628
Successfully built pydotplus
Note: you may need to restart the kernel to use updated packages.
